name: Swift

on:
  push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: [paper]

    steps:
    - uses: actions/checkout@v2
    # Select Xcode version
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode12.2.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
      # Run build
    - name: Build
      run: xcodebuild
            -sdk iphonesimulator
            -configuration Debug
            build
      # Run unit test
